[
("blog-frontend-37a9b57908aaa144.js", include_bytes!(r#"..\resource\asset/blog-frontend-37a9b57908aaa144.js.gz"#), "text/javascript"),
("blog-frontend-37a9b57908aaa144_bg.wasm", include_bytes!(r#"..\resource\asset/blog-frontend-37a9b57908aaa144_bg.wasm.gz"#), "application/wasm"),
("bulma.min-82aac43507618108.css", include_bytes!(r#"..\resource\asset/bulma.min-82aac43507618108.css.gz"#), "text/css"),
("codemirror.min.css", include_bytes!(r#"..\resource\asset/codemirror.min.css.gz"#), "text/css"),
("common.js", include_bytes!(r#"..\resource\asset/common.js.gz"#), "text/javascript"),
("editor.html", include_bytes!(r#"..\resource\asset/editor.html.gz"#), "text/html; charset=utf-8"),
("favicon.ico", include_bytes!(r#"..\resource\asset/favicon.ico.gz"#), ""),
("fontawesome.min-5e9e696c59c57e83.css", include_bytes!(r#"..\resource\asset/fontawesome.min-5e9e696c59c57e83.css.gz"#), "text/css"),
("index-ec4ef66164c33b9c.css", include_bytes!(r#"..\resource\asset/index-ec4ef66164c33b9c.css.gz"#), "text/css"),
("logo.png", include_bytes!(r#"..\resource\asset/logo.png.gz"#), ""),
("regular.min-a0c258fb7c5f655d.css", include_bytes!(r#"..\resource\asset/regular.min-a0c258fb7c5f655d.css.gz"#), "text/css"),
("snippets/blog-frontend-a0e7f15f5414ab99/asset/editor.js", include_bytes!(r#"..\resource\asset/snippets\blog-frontend-a0e7f15f5414ab99\asset\editor.js.gz"#), "text/javascript"),
("snippets/blog-frontend-a0e7f15f5414ab99/asset/show.js", include_bytes!(r#"..\resource\asset/snippets\blog-frontend-a0e7f15f5414ab99\asset\show.js.gz"#), "text/javascript"),
("solid.min-70c2e5caa950974d.css", include_bytes!(r#"..\resource\asset/solid.min-70c2e5caa950974d.css.gz"#), "text/css"),
("toastui-editor-all.min.js", include_bytes!(r#"..\resource\asset/toastui-editor-all.min.js.gz"#), "text/javascript"),
("toastui-editor.min.css", include_bytes!(r#"..\resource\asset/toastui-editor.min.css.gz"#), "text/css"),
("webfonts/fa-brands-400.ttf", include_bytes!(r#"..\resource\asset/webfonts\fa-brands-400.ttf.gz"#), ""),
("webfonts/fa-brands-400.woff2", include_bytes!(r#"..\resource\asset/webfonts\fa-brands-400.woff2.gz"#), ""),
("webfonts/fa-regular-400.ttf", include_bytes!(r#"..\resource\asset/webfonts\fa-regular-400.ttf.gz"#), ""),
("webfonts/fa-regular-400.woff2", include_bytes!(r#"..\resource\asset/webfonts\fa-regular-400.woff2.gz"#), ""),
("webfonts/fa-solid-900.ttf", include_bytes!(r#"..\resource\asset/webfonts\fa-solid-900.ttf.gz"#), ""),
("webfonts/fa-solid-900.woff2", include_bytes!(r#"..\resource\asset/webfonts\fa-solid-900.woff2.gz"#), ""),
]
